from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('details', views.get_details, name="details"),
    path('get_document', views.get_document, name="get document"),
    path('admin/login', views.login, name="login"),
    path('admin/2fa', views.two_factor_auth, name="send 2fa"),
    path('admin/auth', views.authenticate, name="authenticate"),
    path('admin/logout', views.logout, name="logout"),
    path('admin/update', views.update_details, name="update details"),
    path('admin/reset_password', views.reset_password, name="reset password"),
    path('admin/send_forgot_password', views.send_forgot_password_link, name="send forgot password link"),
    path('admin/reset_forgot_password', views.reset_forgotten_password, name="reset forgotten password"),
    path('admin/forgot_password', views.render_forgotten_password_page, name="forgot password"),
    path('admin/upload_profile_picture', views.upload_profile_picture, name="upload profile picture"),
    path('admin/update_bio', views.update_bio, name="update bio"),
    path('admin/upload_document', views.upload_document, name="upload document"),
    path('admin/delete_document', views.delete_document, name="delete document"),
    path('admin/verify', views.verify_email, name="verify email"),
    path('admin/save_address', views.save_address, name="save address"),
    path('admin/add_language', views.add_language, name="add language"),
    path('admin/update_language', views.update_language, name="update language"),
    path('admin/delete_language', views.delete_language, name="delete language"),
    path('admin/add_framework', views.add_framework, name="add framework"),
    path('admin/update_framework', views.update_framework, name="update framework"),
    path('admin/delete_framework', views.delete_framework, name="delete framework"),
    path('admin/add_dbms', views.add_dbms, name="add dbms"),
    path('admin/update_dbms', views.update_dbms, name="update dbms"),
    path('admin/delete_dbms', views.delete_dbms, name="delete dbms"),
    path('admin/add_hobby', views.add_hobby, name="add hobby"),
    path('admin/update_hobby', views.update_hobby, name="update hobby"),
    path('admin/delete_hobby', views.delete_hobby, name="delete hobby"),
    path('admin/add_skill', views.add_skill, name="add skill"),
    path('admin/update_skill', views.update_skill, name="update skill"),
    path('admin/delete_skill', views.delete_skill, name="delete skill"),
    path('admin/add_work', views.add_work, name="add work"),
    path('admin/update_work', views.update_work, name="update work"),
    path('admin/delete_work', views.delete_work, name="delete work"),
    path('admin/add_project', views.add_project, name="add project"),
    path('admin/update_project', views.update_project, name="update project"),
    path('admin/delete_project', views.delete_project, name="delete project"),
    path('admin/add_education', views.add_eduction, name="add education"),
    path('admin/update_education', views.update_education, name="update education"),
    path('admin/delete_education', views.delete_eduction, name="delete education"),
    path('admin/refresh', views.refresh_token_view, name="refresh token"),
]
