# Generated by Django 3.2.9 on 2021-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=30, unique=True)),
                ('confidence', models.CharField(max_length=256)),
                ('avatar', models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='images')),
            ],
        ),
    ]
