# Generated by Django 3.2.9 on 2021-11-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
